baseurl = "/"
languageCode = "fr"
defaultContentLanguage = "fr"
title = "#FreeSenegal - Pour nos morts, rendez leur hommage."
theme = "dream"

[copyright]
  name = "AfricTivistes"
  website = "https://www.africtivistes.org"

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[twitter]
  card = ["img/background.jpg"]
  site = "hommage.free-senegal.org"
  creator = "@AFRICTIVISTES"
  image = ["img/background.jpg"]

[params]
  favicon = "/img/logo.svg"
  description = "FreeSenegal mur d'hommage, pour rendre hommage à nos morts."
  images = ["img/background.jpg"]
  background = "#f7f7f7"
  #backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  # dark mode
  defaultDark = false
  backgroundDark = "black"
  #backgroundImageDark = "/me/background-dark.jpg"
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404 = true

  author = "FreeSenegal"
  # description = ""
  avatar = "/img/avatar.png"
  # headerTitle = ""
  motto = "Pour nos morts, rendez leur hommage."
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  # footerBottomText = ""

  # rss = true

  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""

  email = "g1enyy0ung@gmail.com"
  # twitter = ""
  # facebook = ""
  # instagram = ""
  # mastodon = ""
  # linkedin = ""
  # github = ""
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2016

  # favicon = "/favicon.ico"

  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # search
  # enableSearch = true

  # options
  showSummaryCoverInPost = true
  hasTwitterEmbed = true
  # reversePostAndAside = true

  # [params.advanced]
  #   customCSS = ["css/custom.css"]
  #   customJS = []
