baseurl = "https://www.jammgen3mandats.com/"
languageCode = "fr"
defaultContentLanguage = "fr"
title = "Jàmm a Gën - Initiative citoyenne contre le 3e mandat au Sénégal"
theme = "dream"

[copyright]
  name = "AfricTivistes"
  website = "https://www.africtivistes.org"

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[twitter]
  card = ["img/background.jpg"]
  site = "jammagen.netlify.app"
  creator = "@AFRICTIVISTES"
  image = ["img/background.jpg"]

[params]
  favicon = "/img/logo.svg"
  description = "Initiative citoyenne contre le 3e mandat au Sénégal"
  images = ["img/background.jpg"]
  background = "#f7f7f7"
  backgroundImage = "img/me/background.jpg"
  linkColor = "seagreen"

  # dark mode
  defaultDark = false
  backgroundDark = "#020303"
  backgroundImageDark = "img/me/background-dark.jpg"
  darkLinkColor = "#fff"
  darkNav = true
  dark404 = true

  author = ""
  # description = ""
  avatar = "/img/avatar.png"
  # headerTitle = ""
  motto = "Initiative citoyenne contre le 3e mandat au Sénégal"
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  # footerBottomText = ""

  # rss = true

  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""

  email = "info@africtivistes.org"
  # twitter = ""
  # facebook = ""
  # instagram = ""
  # mastodon = ""
  # linkedin = ""
  # github = ""
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2022

  # favicon = "/favicon.ico"

  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # search
  # enableSearch = true

  # options
  showSummaryCoverInPost = true
  hasTwitterEmbed = true
  # reversePostAndAside = true

  # [params.advanced]
  #   customCSS = ["css/custom.css"]
  #   customJS = []
